version: "3.7"

services:
  kafka-lenses:
    image: landoop/kafka-lenses-dev
    ports:
      - 3030:3030
      - 9092:9092
      - 2181:2181
      - 8081:8081
    environment:
      ADV_HOST: 127.0.0.1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      EULA: https://dl.lenses.stream/d/?id=5a3303e6-b1e5-49da-8d75-c61198f9ed95
    volumes:
      - ./kafka/data/landoop:/data