version: "3.3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: ERROR
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      LOG4J_LOGGER_KAFKA: ERROR
    restart: on-failure:3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  elasticsearch:
    image: elasticsearch:6.4.1
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    privileged: true

  twitter-backwards:
    build: . # OR image: backwards/kafka:latest AFTER docker build -t backwards/kafka .
    environment:
      _JAVA_OPTIONS: "-DKAFKA_BOOTSTRAP_SERVERS.0=kafka:9092 -DELASTIC_SEARCH_SERVERS.0=http://elasticsearch:9200"
    entrypoint: ["java", "-cp", "/beginners-course/target/scala-2.12/beginners-course.jar", "com.backwards.runner.TwitterRunner"]
    restart: on-failure
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
