version: "3.7"

services:
  kafka-lenses:
    image: landoop/kafka-lenses-dev
    ports:
      - 3030:3030
      - 9092:9092
      - 2181:2181
      - 8081:8081
    environment:
      ADV_HOST: 127.0.0.1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      EULA: https://dl.lenses.stream/d/?id=e4204acd-e620-4195-b673-f467f139ee1c

#  cadvisor:
#    image: google/cadvisor
#    ports:
#      - 8080:8080
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro